baseURL = "https://belijzajac.dev"
languageCode = "en-us"
title = "belijzajac.dev"
theme = "minimal-bootstrap-hugo-theme"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  description = "belijzajac's personal blog, where he shows off some of his current, past, and future projects as well as shares personal experience of developing projects involving modern C++ and Linux!"
  aboutAuthor = "Hi there! My online handle on GitHub is belijzajac, which is a Russian translation of \"white hare\". I am a software developer with a strong passion for C++20, Linux, and bare-metal assembly. With a solid foundation in these technologies, I am always looking for new ways to challenge myself and grow as a developer. In my free time, you can find me tinkering with new technologies and keeping up to date with the latest industry trends. Thank you for visiting my blog!"
  selfieAuthor = "author.png"
  stickyImage1 = "shimakaze-says-1.png"
  stickyImage2 = "shimakaze-says-2.png"
  githubLink = "https://github.com/belijzajac"
  emailAddress = "blog@belijzajac.dev"
  navbarColor = "#040a18"
  contentBackgroundColor = "#f5f5e9"
  contentTextColor = "#212529"
  contentLinkColor = "#00254f"
  contentLinkHoverColor = "#000914"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "900px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-217331412-1"
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "gruvbox"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
