baseURL = "https://belijzajac.dev"
languageCode = "en-us"
title = "belijzajac.dev"
theme = "minimal-bootstrap-hugo-theme"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  description = "belijzajac's personal blog, where he shows off some of his current, past, and future projects as well as shares personal experience of developing projects involving modern C++ and Linux!"
  aboutAuthor = "I'm a software developer with a diverse set of interests that include, but are not limited to, bare-metal assembly, Linux, and modern C++20. Since I was a kid, I've been using Linux (since that's what my toaster laptop could handle back in 2010), spreading FUD botnets, performing SQL injections on local WordPress websites, and more. I'm willing to collaborate on projects and can be reached at"
  selfieAuthor = "author.jpg"
  emailAuthor = "$ echo Z2l0aHViQGJlbGlqemFqYWMuZGV2Cg== | base64 -d"
  contentBackgroundTexture = "/white-leather-texture-1945.png"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "900px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-217331412-1"
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
