baseURL = "https://belijzajac.dev"
languageCode = "en-us"
title = "belijzajac.dev"
theme = "minimal-bootstrap-hugo-theme"

[permalinks]
  post = "/:filename/"

[params]
  authorName = "belijzajac"
  authorEmail = "blog@belijzajac.dev"
  authorIntro = "belijzajac (\"white hare\")"
  authorDescription = "Welcome to my personal blog! The content here is independent of my professional work and offers a glimpse into my personal interests."
  description = "belijzajac's personal blog, where he shows off some of his current, past, and future projects as well as shares personal experience of developing projects involving modern C++ and Linux!"
  aboutAuthor = "Hi there! My online handle is belijzajac, which translates to \"white hare\" in Russian. I'm a software developer with a strong passion for C++, Rust, Linux, and compilers. With a solid foundation in these technologies, I'm always looking for new ways to challenge myself and grow as a developer. In my free time, you can find me tinkering with new technologies and keeping up to date with the latest industry trends. Thank you for visiting my blog!"
  selfieAuthor = "author.jpg"
  githubLink = "https://github.com/belijzajac"
  twitterLink = "https://twitter.com/belijzajac"
  emailAddress = "blog@belijzajac.dev"
  selfieAuthorBorderColor = "#d8d8d8"
  navbarColor = "#222121"
  contentTextColor = "#212529"
  contentLinkColor = "#00254f"
  contentLinkHoverColor = "#000914"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  contentPageWidth = "910px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  websiteRunningSince = "2021-12-23"
  googleAnalytics = "UA-217331412-1"
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"
  useGiscus = true
  giscusRepo = "belijzajac/belijzajac.github.io"
  giscusRepoId = "R_kgDOGjWVjg"
  giscusCategory = "Announcements"
  giscusCategoryId = "DIC_kwDOGjWVjs4Cco4S"
  giscusMapping = "pathname"
  giscusStrict = 0
  giscusReactionsEnabled = 1
  giscusEmitMetadata = 0
  giscusInputPosition = "top"
  giscusTheme = "light"
  giscusLang = "en"
  giscusLoading = "lazy"

[menu]
  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "gruvbox"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
